FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04
FROM python:3.10

ENV GRADIO_SERVER_NAME=0.0.0.0
WORKDIR /roop

RUN apt-get update
RUN apt-get install -y ffmpeg

RUN git clone https://github.com/s0md3v/roop.git .
RUN git checkout next
RUN pip install -r requirements-docker.cuda.txt
