name: ci

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: pip install flake8
      - run: flake8 run.py core

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: CPU
            run: ./run.py -f=.github/examples/face.jpg -t=.github/examples/target.mp4 -o=.github/examples/output.mp4
          - name: GPU (NVIDIA)
            run: ./run.py -f=.github/examples/face.jpg -t=.github/examples/target.mp4 -o=.github/examples/output.mp4 --gpu-vendor=nvidia
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: pip install -r requirements.txt gdown
      - run: gdown https://drive.google.com/uc?id=13QpWFWJ37EB-nHrEOY64CEtQWY-tz7DZ
      - run: ${{ matrix.run }}
      - run: ffmpeg -i .github/examples/snapshot.mp4 -i .github/examples/output.mp4 -filter_complex "psnr" -f null /dev/null
      - run: cp .github/examples/output.mp4 docs/examples/latest-test.mp4
      - name: Upload output artifact
        if: github.ref == 'refs/heads/main' # Only runs if the branch is 'main'
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: docs/examples/latest-test.mp4
      - name: Configure Git
        run: |
          git config --global user.name "Roop CI"
          git config --global user.email "noreply@example.com"
      - name: Commit and Push
        if: github.ref == 'refs/heads/main' # Only runs if the branch is 'main'
        run: |
          git add docs/examples/latest-test.mp4 || true
          git commit -m ":white_check_mark: Test completed! Updates latest-test.mp4" || true
          git push || true
